name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: "https://wakapi.asahoo.dev/api"
          LANG_COUNT: 6
          SHOW_TIME: true
          SHOW_TOTAL: false
          SHOW_TITLE: false
          TIME_RANGE: "last_7_days"


